init:
  image:
    repository: vit0r/nominatim-init
    pullPolicy: Always
    tag: ~
  pbf_url: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
nominatim:
  replicaCount: 1
  image:
    repository: vit0r/nominatim
    pullPolicy: Always
    tag: ~
  serviceAccount:
    create: true
    annotations: {}
    name: "nominatim"
  podAnnotations: {}
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
  podSecurityContext: {}
  persistence:
    storageClassName: nfs
  service:
    type: ClusterIP
    port: 8000
  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts:
      - host: nominatim.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: nominatim-tls
    #    hosts:
    #      - nominatim.local
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
postgres:
  replicaCount: 1
  image:
    repository: vit0r/postgres
    pullPolicy: IfNotPresent
    tag: 13
  imagePullSecrets: []
  podAnnotations: {}
  persistence:
    storageClassName: nfs
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
  service:
    type: ClusterIP
    port: 5432
  resources:
    # limits:
    {}
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
nameOverride: "nominatim"
fullnameOverride: "nominatim"
