apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nominatim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.nominatim.autoscaling.enabled }}
  replicas: {{ .Values.nominatim.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nominatim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nominatim.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nominatim.selectorLabels" . | nindent 8 }}
    spec:
      setHostnameAsFQDN: true
      {{- with .Values.nominatim.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nominatim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nominatim.podSecurityContext | nindent 8 }}
      initContainers:
        - name: nominatim-download-pbf
          securityContext:
            {{- toYaml .Values.nominatim.securityContext | nindent 12 }}
          image: "{{ .Values.nominatim.image.repository }}:{{ .Values.nominatim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nominatim.image.pullPolicy }}
          command: ["/init"] 
          env:
            - name: NOMINATIM_PBF
              value: {{ .Values.init.pbf_url }} 
          volumeMounts:
            - name: nominatim
              mountPath: /data
      containers:
        - name: postgresql
          securityContext:
            {{- toYaml .Values.postgres.securityContext | nindent 12 }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: nominatim
            - name: POSTGRES_PASSWORD
              value: nominatim
            - name: POSTGRES_DB
              value: nominatim
            - name: PGDATA
              value: /data/postgres
            - name: LANG
              value: en_US.utf8
          ports:
            - name: tcp
              containerPort: {{.Values.postgres.service.port}}
              protocol: TCP
              port: {{.Values.postgres.service.port}}
          volumeMounts:
            - name: postgres-data
              mountPath: /data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.nominatim.securityContext | nindent 12 }}
          image: "{{ .Values.nominatim.image.repository }}:{{ .Values.nominatim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nominatim.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nominatim.containerPort | default 8000 }}
              protocol: TCP
          env:
            - name: NOMINATIM_DATABASE_DSN
              value: pgsql:host=localhost;port={{.Values.postgres.service.port}};user=nominatim;password=nominatim;dbname=nominatim
            - name: NOMINATIM_VERSION
              value: {{ .Chart.AppVersion }}
            - name: NOMINATIM_IMPORT_STYLE
              value: {{ .Values.nominatim.import_style | default "address" }}
          livenessProbe:
            tcpSocket:
              port: {{.Values.postgres.service.port}}
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: nominatim
              mountPath: /data
          resources:
            {{- toYaml .Values.nominatim.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nominatim
          persistentVolumeClaim:
            claimName: nominatim
        - name: postgres-data
          persistentVolumeClaim:
            claimName: nominatim-postgres
        # - name: postgres-run
        #   persistentVolumeClaim:
        #     claimName: nominatim-postgres
