apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nominatim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.nominatim.autoscaling.enabled }}
  replicas: {{ .Values.nominatim.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nominatim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nominatim.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nominatim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nominatim.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nominatim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nominatim.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          securityContext:
            {{- toYaml .Values.postgres.securityContext | nindent 12 }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
              port: 5432
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.nominatim.securityContext | nindent 12 }}
          image: "{{ .Values.nominatim.image.repository }}:{{ .Values.nominatim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nominatim.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nominatim.containerPort | default 8080 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nominatim.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
