apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nominatim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nominatim.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 50G
  accessModes:
    - ReadWriteOnce