{{- if .Values.nominatim.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nominatim.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
  {{- with .Values.nominatim.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.postgres.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nominatim.serviceAccountName" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
  {{- with .Values.postgres.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
