name: nominatim
on:
  push:
    branches:
      - main
    paths:
      - "image/**"
jobs:
  registry:
    name: deploy nominatim
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: login into registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push image
        run: ./deploy.sh ${{ github.run_number }}
